server:
  port: 8080

spring:
  profiles:
    include:
      - jpa

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
  paths-to-match:
    - /api/v1/**

