server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myongsik?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1q2w3e4r!

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 20
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace