server:
  port: 8080

spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 20
    open-in-view: false

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
  paths-to-match:
    - /api/v1/**

